const API_URL = process.env.REACT_APP_API_URL;
const CDN_IMAGE_URL = process.env.REACT_APP_CDN_IMAGE_URL;
const CDN_AUDIO_URL = process.env.REACT_APP_CDN_AUDIO_URL;
const FACEBOOK_APP_ID = process.env.REACT_APP_FACEBOOK_APP_ID;
export { API_URL, CDN_IMAGE_URL, CDN_AUDIO_URL, FACEBOOK_APP_ID };
